### ISSUE TITLE
Course codes from Open AUTh

### ISSUE THREAD

**Issue by sakrifor** [acmauth/MLGrade#1]
We need to make use of the course codes found in https://ws-ext.it.auth.gr/swagger/ rather the course codes starting with "NCO-". This has to be done in order for the ML part to be compatible with the backend part which uses these codes. To get these codes you need to execute the /open/getStudiesProgCourses/{prId} with prID = 600000438 which is the current study program. @GregB712 or @Mavioux is any of you willing to do this?

**Comment by GregB712** [comment]
I'm on it.
